[package]
name = "vhdesk-transport"
description = "Transporte QUIC, NAT traversal, relay y control de congestion."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
vhdesk-proto.workspace = true

bytes.workspace = true
quinn.workspace = true
rcgen.workspace = true
rustls.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
anyhow.workspace = true
tracing-subscriber.workspace = true

[[example]]
name = "echo"
