[package]
name = "vhdesk-codec"
description = "Codificacion y decodificacion de video tras traits comunes, por software y por hardware."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
vhdesk-libvpx-sys.workspace = true
vhdesk-proto.workspace = true

bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true
yuv.workspace = true

[dev-dependencies]
anyhow.workspace = true
vhdesk-capture.workspace = true
yuv.workspace = true

[[example]]
name = "bench-yuv"
